name: hainlinegripes
favicon: null
layout_spectrum: 0.01948
typography_spectrum: 0.02994
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.875
  lightness: 0.8937153085134923
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
